# =====> User <=====

### Register User
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "fullname" : "Jamilu Salisu", 
    "regNumber" : "CST/19/SWE", 
    "phoneNumber" : "08028752833", 
    "emailAddress" : "admin@email.com", 
    "password" : "admin"
}

### All Users
GET http://127.0.0.1:5000/users

### Reset User Password
PATCH http://127.0.0.1:5000/reset-password
Content-Type: application/json

{
    "emailAddress" : "admin@email.com"
}

# =====> User Avatar <=====

# =====> User Proof of Identification <=====

# =====> User Logs <=====

# =====> Item Registration <=====

# =====> Item Movement <=====
